<?php

namespace ContainerKs68Klj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Soq8KgKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.soq8KgK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.soq8KgK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'usersRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'usersRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
