<?php

namespace ContainerX8ppO4h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6GJGHP2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6GJGHP2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6GJGHP2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'promotion' => ['privates', '.errored..service_locator.6GJGHP2.App\\Entity\\Promotion', NULL, 'Cannot autowire service ".service_locator.6GJGHP2": it references class "App\\Entity\\Promotion" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'promotion' => 'App\\Entity\\Promotion',
        ]);
    }
}
