<?php

namespace ContainerX8ppO4h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOffresService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ORQASky.App\Entity\Offres' shared service.
     *
     * @return \App\Entity\Offres
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ORQASky": it references class "App\\Entity\\Offres" but no such service exists.');
    }
}
