<?php

namespace ContainerX8ppO4h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSponsor2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.x.UtaSh.App\Entity\Sponsor' shared service.
     *
     * @return \App\Entity\Sponsor
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.x.UtaSh": it references class "App\\Entity\\Sponsor" but no such service exists.');
    }
}
