<?php

namespace ContainerDfwrZCv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlanning2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vYJJTqk.App\Entity\Planning' shared service.
     *
     * @return \App\Entity\Planning
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.vYJJTqk": it references class "App\\Entity\\Planning" but no such service exists.');
    }
}
