<?php

namespace ContainerUOmgcqA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivite2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vj0fnNa.App\Entity\Activite' shared service.
     *
     * @return \App\Entity\Activite
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.vj0fnNa": it references class "App\\Entity\\Activite" but no such service exists.');
    }
}
