<?php

namespace ContainerX8ppO4h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X_UtaShService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x.UtaSh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x.UtaSh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sponsor' => ['privates', '.errored..service_locator.x.UtaSh.App\\Entity\\Sponsor', NULL, 'Cannot autowire service ".service_locator.x.UtaSh": it references class "App\\Entity\\Sponsor" but no such service exists.'],
        ], [
            'sponsor' => 'App\\Entity\\Sponsor',
        ]);
    }
}
