<?php

namespace ContainerX8ppO4h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NB8NDQMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nB8NDQM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nB8NDQM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'offre' => ['privates', '.errored..service_locator.nB8NDQM.App\\Entity\\Offres', NULL, 'Cannot autowire service ".service_locator.nB8NDQM": it references class "App\\Entity\\Offres" but no such service exists.'],
        ], [
            'offre' => 'App\\Entity\\Offres',
        ]);
    }
}
