<?php

namespace ContainerX8ppO4h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dq01r_ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Dq01r.Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Dq01r.Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'sponsor' => ['privates', '.errored..service_locator.Dq01r.Z.App\\Entity\\Sponsor', NULL, 'Cannot autowire service ".service_locator.Dq01r.Z": it references class "App\\Entity\\Sponsor" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'sponsor' => 'App\\Entity\\Sponsor',
        ]);
    }
}
