<?php

namespace ContainerX8ppO4h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotion2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.B8XuQBd.App\Entity\Promotion' shared service.
     *
     * @return \App\Entity\Promotion
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.B8XuQBd": it references class "App\\Entity\\Promotion" but no such service exists.');
    }
}
