#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# routes.yaml
block_user:
    path: '/block/user/{id}'
    controller: 'YourController::blockUser'

admin_users_delete:
    path: /admin/utilisateurs/{id}/supprimer
    controller: 'App\Controller\Admin\UserController::deleteUser'
    methods: [POST]

    