<?php

namespace ContainerAJRMxmi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vj0fnNaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vj0fnNa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vj0fnNa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Normalizer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
            'activite' => ['privates', '.errored..service_locator.vj0fnNa.App\\Entity\\Activite', NULL, 'Cannot autowire service ".service_locator.vj0fnNa": it references class "App\\Entity\\Activite" but no such service exists.'],
        ], [
            'Normalizer' => '?',
            'activite' => 'App\\Entity\\Activite',
        ]);
    }
}
