<?php

namespace ContainerAJRMxmi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchebTwoFactor_Security_Email_CodeGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'scheb_two_factor.security.email.code_generator' shared service.
     *
     * @return \Scheb\TwoFactorBundle\Security\TwoFactor\Provider\Email\Generator\CodeGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'scheb'.\DIRECTORY_SEPARATOR.'2fa-email'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'TwoFactor'.\DIRECTORY_SEPARATOR.'Provider'.\DIRECTORY_SEPARATOR.'Email'.\DIRECTORY_SEPARATOR.'Generator'.\DIRECTORY_SEPARATOR.'CodeGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'scheb'.\DIRECTORY_SEPARATOR.'2fa-email'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'TwoFactor'.\DIRECTORY_SEPARATOR.'Provider'.\DIRECTORY_SEPARATOR.'Email'.\DIRECTORY_SEPARATOR.'Generator'.\DIRECTORY_SEPARATOR.'CodeGenerator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'scheb'.\DIRECTORY_SEPARATOR.'2fa-email'.\DIRECTORY_SEPARATOR.'Mailer'.\DIRECTORY_SEPARATOR.'AuthCodeMailerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'scheb'.\DIRECTORY_SEPARATOR.'2fa-email'.\DIRECTORY_SEPARATOR.'Mailer'.\DIRECTORY_SEPARATOR.'SymfonyAuthCodeMailer.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->services['scheb_two_factor.security.email.code_generator'])) {
            return $container->services['scheb_two_factor.security.email.code_generator'];
        }

        return $container->services['scheb_two_factor.security.email.code_generator'] = new \Scheb\TwoFactorBundle\Security\TwoFactor\Provider\Email\Generator\CodeGenerator($container->load('getSchebTwoFactor_Persister_DoctrineService'), new \Scheb\TwoFactorBundle\Mailer\SymfonyAuthCodeMailer($a, 'no-reply@test.com', 'no-reply'), 6);
    }
}
