<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUOmgcqA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUOmgcqA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUOmgcqA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUOmgcqA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUOmgcqA\App_KernelDevDebugContainer([
    'container.build_hash' => 'UOmgcqA',
    'container.build_id' => '748473fb',
    'container.build_time' => 1709667591,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUOmgcqA');
