<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCqxE4n5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCqxE4n5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCqxE4n5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCqxE4n5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCqxE4n5\App_KernelDevDebugContainer([
    'container.build_hash' => 'CqxE4n5',
    'container.build_id' => 'adc08066',
    'container.build_time' => 1708104120,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCqxE4n5');
