<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVNchQJH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVNchQJH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVNchQJH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVNchQJH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVNchQJH\App_KernelDevDebugContainer([
    'container.build_hash' => 'VNchQJH',
    'container.build_id' => 'a36673f4',
    'container.build_time' => 1709479241,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVNchQJH');
