<?php

namespace ContainerQpmuxIi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZC_CutQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zC.cutQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zC.cutQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
            'progressBarRepository' => ['privates', '.errored.Ba.bxgS', NULL, 'Cannot determine controller argument for "App\\Controller\\AbonnementController::stripePaymentSuccess()": the $progressBarRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\ProgressBarRepository". Did you forget to add a use statement?'],
        ], [
            'managerRegistry' => '?',
            'progressBarRepository' => '?',
        ]);
    }
}
