<?php

namespace ContainerQpmuxIi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Ba_BxgSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.Ba.bxgS' shared service.
     *
     * @return \App\Controller\ProgressBarRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\AbonnementController::stripePaymentSuccess()": the $progressBarRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\ProgressBarRepository". Did you forget to add a use statement?');
    }
}
